### ISSUE TITLE
GIE Storage Download

### ISSUE THREAD

**Issue by joph** [petres/energy#13]
For some reason, the download of storage data from GIE does not work fully. I could reproduce locally, that the data from year 2019 is simply not returned by agsi.gie.eu, although the request string looks correct and data from the year 2018 is returned. However, the data is not even shown on their web interface (https://agsi.gie.eu/), i.e. selecting 2019 gives an error, so I am pretty sure this is related to some problem at gie.eu. However, if we had some backup of older data, we could fill in 2019. I don't unfortunately...

**Comment by petres** [comment]
I have also observed this, seems like they sometimes provide strange data. Let's look how often that occurs.

**Comment by petres** [comment]
Previous years are now cached
