### ISSUE TITLE
holidays.csv not commited

### ISSUE THREAD

**Issue by joph** [petres/energy#16]
The file is not in the repository, could you commit? Or is it produced by another script?
https://github.com/petres/energy/blob/8bd04b22832d799f81a150acf0923aaca0041ba3/prep/calc/prediction-gas-consumption/linearModel1-new.r#L20

**Comment by petres** [comment]
Should be there:
[/prep/load/holidays.r#L64](https://github.com/petres/energy/blob/8bd04b22832d799f81a150acf0923aaca0041ba3/prep/load/holidays.r#L64)
