### ISSUE TITLE
Unit error

### ISSUE THREAD

**Issue by joph** [petres/energy#9]
https://github.com/petres/energy/blob/6b205d0b973b909238e23cdec19a16ec8ac311ca/web/data/electricity/generation/def-facets.json#L8

Should be GWh instead of MWh.

**Comment by petres** [comment]
Sure?

**Comment by joph** [comment]
100%. Here https://github.com/petres/energy/blob/0718ed4cc87e5141ad5e668dc8157e6e8b80633c/prep/load/entsoe/generation-facets.r#L18 you divide by 10^3. The data is given in MWh, so this will convert to GWh.

**Comment by petres** [comment]
Fixed in ac1ba893e849796dd4e2ae8aca1ab22a738164fc
